# Global information
source-id: "axelar-dojo-1"
config-version: 1
properties:
  title: "Axelar"
  hex: "#5cc1fa"
  logo: "ar://iW1jN99yH_gdQtRhf5J_lVwOIu8p_i7FyxEgoQAkWxU"

networks:
  # Mainnet pools
  kyve-1:
    pools:
      - id: 3
        runtime: "kyvejs/tendermint"
    integrations:
      ksync:
        binary-name: "axelard"
        block-sync-pool: 3
        docs-url: "https://docs.axelar.dev/"

  # Testnet pools
  kaon-1:
    pools:
      - id: 1
        runtime: "kyvejs/tendermint"
    integrations:
      ksync:
        binary-name: "axelard"
        block-sync-pool: 3
        docs-url: "https://docs.axelar.dev/"